services:
  api-gateway:
    command: ["npm", "run", "dev", "--", "--inspect=0.0.0.0:9200"]
    ports:
      - 9200:9200
    volumes:
      - ./api-gateway:/app
  fibonacci:
    command: ["npm", "run", "dev", "--", "--inspect=0.0.0.0:9300"]
    ports:
      - 9300:9300
    volumes:
      - ./fibonacci:/app
  http-proxy:
    build:
      context: ./http-proxy
      dockerfile: http-proxy.dev.Dockerfile
    depends_on:
      - web-app
    volumes:
      - ./http-proxy/etc/nginx/conf.d/dev.nginx.conf:/etc/nginx/conf.d/dev.nginx.conf
  web-app:
    build:
      context: ./web-app
      dockerfile: ../node.prod.Dockerfile
    command: ["npm", "run", "dev", "--", "-p", "3000"]
    container_name: web-app
    depends_on:
      - api-gateway
    networks:
      - front
    ports:
      - 3000:3000
    volumes:
      - ./web-app:/app
version: "3"
